language: python
python:
- "3.7"

env:
- DJANGO_VERSION=1.11.24

install:
- pip install -r requirements.txt

script:
- coverage run --source='.' manage.py test --settings=settings.test

after_success:
- coveralls
