# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-04 18:24
from __future__ import unicode_literals

from django.db import migrations



def create_priorities(apps, schema_editor):
    Priority = apps.get_model('app', 'Priority')
    priority_names = ['Low', 'Medium', 'High']
    for name in priority_names:
        Priority.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_priorities),
    ]
