# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-04 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190904_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'created']},
        ),
    ]
